// declarative pipeline simplified syntax for defining the pipeline
// contains all definitions of jenkins pipeline

pipeline{
    //Directives
    agent any

    stages {
        // Specify various stage with in stages

        // stage 1. Build
        stage ('Build'){
            steps {
                echo ' building......'
            }
        }

        // Stage2 : Testing
        stage ('Test'){
            steps {
                echo ' testing......'

            }
        }

        // Stage3 : Publish the artifacts to Nexus
        stage ('Deploy'){
            steps {
                echo ' deploying......'
            }
        }

    }

}