pipeline {
    agent {
        docker {
            image 'node:6-alpine'
            args '-p 3000:3000'
        }
    }
    environment {
        CI = 'true'
    }
    
    // stage 1. Build
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
          // Stage2 : Testing
        stage ('Test'){
            steps {
                echo ' testing......'

            }
        }

       // Stage3 : Publish the artifacts to Nexus
        stage ('Deploy'){
            steps {
                echo ' deploying......'
            }
        }
    }
}