pipeline {
  agent any
    
  tools {nodejs "node"}
    
    // stage 1. Build
    stages {
        stage('Build') {
            steps {
                dir('/var/lib/jenkins/workspace/app/client/') {
                    sh "npm install"
                }
            }
            steps {
                dir('/var/lib/jenkins/workspace/app/server/') {
                    sh "npm install"
                }
            }
        }

          // Stage2 : Testing
        stage ('Test'){
            steps {
                echo ' testing......'

            }
        }

       // Stage3 : Publish the artifacts to Nexus
        stage ('Deploy'){
            steps {
                echo ' deploying......'
            }
        }
    }
}