pipeline {
  agent any
    
  tools {
      nodejs "node"
    }

    environment{
       ArtifactId = readMavenPom().getArtifactId()
       Version = readMavenPom().getVersion()
       Name = readMavenPom().getName()
       GroupId = readMavenPom().getGroupId()
    }
    
    // stage 1. Build
    stages {
        stage('Build') {
            steps {
                dir('/var/lib/jenkins/workspace/client/app/client/') {
                    sh "npm install"
                }
            }
        }

          // Stage2 : Testing
        stage ('Test'){
            steps {
                echo ' testing......'

            }
        }

        // Stage3: Publishing artifacts to nexus
        stage ('Publishing'){
               steps {
                dir('/var/lib/jenkins/workspace/client/app/client/') {
                    sh "npm publish"
                    sh 'npm whoami'
                    sh 'rm .npmrc'
                }
            }
        }
        

       // Stage4: Publish the artifacts to Nexus
        stage ('Deploy'){
            steps {
                echo ' deploying......'
            }
        }
    }
}

