pipeline {
  agent any
    
  tools {
      nodejs "node"
    }
        
    // stage 1. Build
    stages {
        stage('Build') {
            steps {
                dir('/var/lib/jenkins/workspace/client/app/client/') {
                    sh "npm install"
                }
            }
        }

          // Stage2 : Testing
        stage ('Test'){
            steps {
                echo ' testing......'

            }
        }

        // Stage3: Publishing artifacts to nexus
        stage ('Publishing'){
               steps {
                    dir('/var/lib/jenkins/workspace/client/app/client/') {
                        sh "npm publish"
                        sh 'npm whoami'
                        sh 'rm .npmrc'
                        sh 'npm set --registry http://18.185.136.129:8081/repository/npm-private/ _auth=YWRtaW46YWRtaW4xMjM='
                        sh 'npm adduser --registry http://18.185.136.129:8081/repository/npm-private/ --always-auth'

                }
            }
        }
        

       // Stage4: Publish the artifacts to Nexus
        stage ('Deploy'){
            steps {
                echo ' deploying......'
            }
        }
    }
}

