pipeline {
  agent any
    
  tools {nodejs "node"}
    
    // stage 1. Build
    stages {
        stage('Build') {
            steps {
                dir('/var/lib/jenkins/workspace/client/app/client/') {
                    sh "npm install"
                }
            }
        }

          // Stage2 : Testing
        stage ('Test'){
            steps {
                echo ' testing......'

            }
        }

        // Stage3: Publishing artifacts to nexus
        stage ('Publishing'){
            steps {
                nexusArtifactUploader artifacts: [[artifactId: 'tanjapolz', classifier: '', file: 'target/com.devopsproject-0.0.5-SNAPSHOT.war', type: 'war']], credentialsId: '38cc8635-b552-4aad-b98f-0e36d6a1eab5', groupId: 'com.devopsproject', nexusUrl: '172.20.10.170:8081', nexusVersion: 'nexus3', protocol: 'http', repository: 'devops-client-SNAPSHOT', version: '0.0.5-SNAPSHOT'
            }
        }

       // Stage4: Publish the artifacts to Nexus
        stage ('Deploy'){
            steps {
                echo ' deploying......'
            }
        }
    }
}

